### ISSUE TITLE
office365_odata_base/office365_odata_base.h file not found issue.

### ISSUE THREAD

**Issue by prakashRavi1990** [jasonjoh/swift-tutorial#1]
I am following the below tutorial where I found the Office365 Pod. 
[(https://dev.outlook.com/restapi/tutorial/ios#)](url)

I followed all the steps and I am getting the following issue.

#import <office365_odata_base/office365_odata_base.h> getting file not found issue.

I have added the pods but getting this issue.

Thanks in  advance.

**Comment by jasonjoh** [comment]
Sorry to hear you're having trouble. I'm actually pushing an update to this today that eliminates the use of those pods.

**Comment by prakashRavi1990** [comment]
@jasonjoh Thank you for your time to reply. 
I am waiting for your push.  

Once again thanks !

**Comment by jasonjoh** [comment]
Just pushed the latest commit. Enjoy the new version!
