### ISSUE TITLE
Outlook Calendar API returning only the first event

### ISSUE THREAD

**Issue by hamedazhar-giz** [jasonjoh/swift-tutorial#10]
I followed the [Adding Calendar and Contacts APIs](https://docs.microsoft.com/en-us/outlook/rest/ios-tutorial#adding-calendar-and-contacts-apis) for syncing events from Outlook account.

```
func getEvents(callback: @escaping (JSON?) -> Void) -> Void {
let apiParams = [
    "$select": "subject,start,end",
    "$orderby": "start/dateTime ASC",
    "$top": "10"
]
makeApiCall(api: "/v1.0/me/events", params: apiParams) {
    result in
    callback(result)
   }
}

func makeApiCall(api: String, params: [String: String]? = nil, callback: @escaping (JSON?) -> Void) -> Void {
    //authorize
    oauth2.authorize {  authParameters, error  in
        if let params = authParameters {
            print("Authorized! Additional parameters: \(params)")
        }`

    }
    // Build the request URL

    var urlBuilder = URLComponents(string: "https://graph.microsoft.com")!
    urlBuilder.path = api

    if let unwrappedParams = params {
        // Add query parameters to URL
        urlBuilder.queryItems = [URLQueryItem]()
        for (paramName, paramValue) in unwrappedParams {
            urlBuilder.queryItems?.append(
                URLQueryItem(name: paramName, value: paramValue))
        }
    }

    let apiUrl = urlBuilder.url!
    NSLog("Making request to \(apiUrl)")

    var req = oauth2.request(forURL: apiUrl)
    req.addValue("application/json", forHTTPHeaderField: "Accept")

    let loader = OAuth2DataLoader(oauth2: oauth2)

    loader.perform(request: req) {
        response in
        do {
            let dict = try response.responseJSON()
            DispatchQueue.main.async {
                let result = JSON(dict)
                callback(result)
            }
        }
        catch let error {
            DispatchQueue.main.async {
                let result = JSON(error)
                callback(result)
            }
        }
    }
}
```

I am calling these functions in order to get all the events in Outlook account to sync with my iOS app. But I am just getting the first event only! They tutorial does not contain any sample codes to check, due to this I'm stuck for hours. Any help would be much appreciated!

Please refer: [SO link](https://stackoverflow.com/questions/51062279/outlook-calendar-api-returning-only-the-first-event)

**Comment by jasonjoh** [comment]
I'm not sure what to tell you here, other than the API will return at most 10 events (`"$top": "10"`), and if you're only getting one event, it's probably because you only have one event on the calendar.

You might want to check your results by going to the [Graph Explorer](https://developer.microsoft.com/en-us/graph/graph-explorer), logging in with the same account, then running the same query.

**Comment by hamedazhar-giz** [comment]
After using Graph Explorer, I understood the issue. The repeating events are not returning!! Only the non-recurring ones are! 
For eg, if a meeting is scheduled in every weekday morning say, Mon to Fri 10:00 to 11:00, those events are not being returned from the Graph API. Any idea?

**Comment by jasonjoh** [comment]
When you query `/events` you get all single-instance appointments and the series master of recurring events, as [documented](https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/api/user_list_events). If you want to get a list of the occurrences of a recurring event, you should use a [calendar view query](https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/api/calendar_list_calendarview) instead.

**Comment by hamedazhar-giz** [comment]
OMG!! That was my issue! Thanks a lot!
