### ISSUE TITLE
loop

### ISSUE THREAD

**Issue by sivaprasad3175** [jasonjoh/swift-tutorial#11]
is it possible to maintain the mail content obtained in the form of loop and display them in tableview

**Comment by jasonjoh** [comment]
Closing this issue as I'm archiving this sample. We've retired the tutorial that this is based on and we're redirecting to the Microsoft Graph tutorial at https://docs.microsoft.com/graph/tutorials/ios-swift. The corresponding GitHub repo is https://github.com/microsoftgraph/msgraph-training-ios-swift.
