### ISSUE TITLE
Crashes at login

### ISSUE THREAD

**Issue by xcodeApps** [jasonjoh/swift-tutorial#2]
Thanks for the sample.  App is crashing on submitting email/password on accounts page. 
I am checking this on xcode 9 iOS 11, Simulators 8 plus.
Below is the crash log it looks like web delegate has some issue 
017-10-14 00:57:50.644888+0530 swift-tutorial[74308:3908016] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Completion handler passed to -[p2_OAuth2.OAuth2WebViewController webView:decidePolicyForNavigationAction:decisionHandler:] was called more than once'
*** First throw call stack:
(
	0   CoreFoundation                      0x00000001065461cb __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00000001031a9f41 objc_exception_throw + 48
	2   CoreFoundation                      0x00000001065bab95 +[NSException raise:format:] + 197
	3   WebKit                              0x00000001144e67f7 _ZNK6WebKit28CompletionHandlerCallChecker30completionHandlerHasBeenCalledEv + 203
	4   WebKit                              0x00000001145289a3 _ZZN6WebKit15NavigationState16NavigationClient31decidePolicyForNavigationActionERNS_12WebPageProxyERN3API16NavigationActionEON3WTF3RefINS_27WebFramePolicyListenerProxyEEEPNS4_6ObjectEEN3$_1clE24WKNavigationActionPolicyP18_WKWebsitePolicies + 31
	5   p2_OAuth2                           0x0000000102adb5a0 _T0SC24WKNavigationActionPolicyOIyBy_ABIxy_TR + 32
	6   p2_OAuth2                           0x0000000102adb62a _T0SC24WKNavigationActionPolicyOIyBy_ABIxy_TRTA + 58
	7   p2_OAuth2                           0x0000000102adb451 _T09p2_OAuth20B17WebViewControllerC03webD0ySo05WKWebD0C_So18WKNavigationActionC15decidePolicyForySC0hiK0Oc15decisionHandlertF + 3297
	8   p2_OAuth2                           0x0000000102adb56c _T09p2_OAuth20B17WebViewControllerC03webD0ySo05WKWebD0C_So18WKNavigationActionC15decidePolicyForySC0hiK0Oc15decisionHandlertFTo + 156
	9   WebKit                              0x00000001145266eb _ZN6WebKit15NavigationState16NavigationClient31decidePolicyForNavigationActionERNS_12WebPageProxyERN3API16NavigationActionEON3WTF3RefINS_27WebFramePolicyListenerProxyEEEPNS4_6ObjectE + 1049
	10  WebKit                              0x0000000114688b5a _ZN6WebKit12WebPageProxy31decidePolicyForNavigationActionEyRKN7WebCore18SecurityOriginDataEyRKNS_20NavigationActionDataERKNS_13FrameInfoDataEyRKNS1_15ResourceRequestESD_yRKNS_8UserDataEON3WTF3RefIN8Messages12WebPageProxy31DecidePolicyForNavigationAction12DelayedReplyEEE + 1144
	11  WebKit                              0x00000001146ae792 _ZN3IPC22callMemberFunctionImplIN6WebKit12WebPageProxyEMS2_FvyRKN7WebCore18SecurityOriginDataEyRKNS1_20NavigationActionDataERKNS1_13FrameInfoDataEyRKNS3_15ResourceRequestESF_yRKNS1_8UserDataEON3WTF3RefIN8Messages12WebPageProxy31DecidePolicyForNavigationAction12DelayedReplyEEEESO_NSt3__15tupleIJyS4_yS7_SA_ySD_SD_ySG_EEEJLm0ELm1ELm2ELm3ELm4ELm5ELm6ELm7ELm8ELm9EEEEvPT_T0_ONSK_IT1_EEOT2_NST_16integer_sequenceImJXspT3_EEEE + 98
	12  WebKit                              0x00000001146a9018 _ZN3IPC20handleMessageDelayedIN8Messages12WebPageProxy31DecidePolicyForNavigationActionEN6WebKit12WebPageProxyEMS5_FvyRKN7WebCore18SecurityOriginDataEyRKNS4_20NavigationActionDataERKNS4_13FrameInfoDataEyRKNS6_15ResourceRequestESI_yRKNS4_8UserDataEON3WTF3RefINS3_12DelayedReplyEEEEEEvRNS_10ConnectionERNS_7DecoderERNSt3__110unique_ptrINS_7EncoderENSX_14default_deleteISZ_EEEEPT0_T1_ + 319
	13  WebKit                              0x000000011452406d _ZN3IPC18MessageReceiverMap19dispatchSyncMessageERNS_10ConnectionERNS_7DecoderERNSt3__110unique_ptrINS_7EncoderENS5_14default_deleteIS7_EEEE + 141
	14  WebKit                              0x00000001146f61b2 _ZN6WebKit15WebProcessProxy21didReceiveSyncMessageERN3IPC10ConnectionERNS1_7DecoderERNSt3__110unique_ptrINS1_7EncoderENS6_14default_deleteIS8_EEEE + 28
	15  WebKit                              0x00000001144e929d _ZN3IPC10Connection19dispatchSyncMessageERNS_7DecoderE + 203
	16  WebKit                              0x00000001144e6c38 _ZN3IPC10Connection15dispatchMessageENSt3__110unique_ptrINS_7DecoderENS1_14default_deleteIS3_EEEE + 104
	17  WebKit                              0x00000001144e94ba _ZN3IPC10Connection18dispatchOneMessageEv + 176
	18  JavaScriptCore                      0x00000001101072a9 _ZN3WTF7RunLoop11performWorkEv + 169
	19  JavaScriptCore                      0x0000000110107562 _ZN3WTF7RunLoop11performWorkEPv + 34
	20  CoreFoundation                      0x00000001064e92b1 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	21  CoreFoundation                      0x0000000106588d31 __CFRunLoopDoSource0 + 81
	22  CoreFoundation                      0x00000001064cdc19 __CFRunLoopDoSources0 + 185
	23  CoreFoundation                      0x00000001064cd1ff __CFRunLoopRun + 1279
	24  CoreFoundation                      0x00000001064cca89 CFRunLoopRunSpecific + 409
	25  GraphicsServices                    0x000000010bacc9c6 GSEventRunModal + 62
	26  UIKit                               0x0000000103778d30 UIApplicationMain + 159
	27  swift-tutorial                      0x00000001026d9d67 main + 55
	28  libdyld.dylib                       0x0000000107d23d81 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
![simulator screen shot - iphone 6s plus - 2017-10-14 at 00 57 00](https://user-images.githubusercontent.com/32763714/31563017-28cad27a-b07b-11e7-9829-61b16ea24fb0.png)
![simulator screen shot - iphone 6s plus - 2017-10-14 at 00 57 00](https://user-images.githubusercontent.com/32763714/31563043-33e9c5f8-b07b-11e7-8deb-2141975e821c.png)
![simulator screen shot - iphone 6s plus - 2017-10-14 at 00 57 41](https://user-images.githubusercontent.com/32763714/31563044-3434feb0-b07b-11e7-911d-c2f75c0130b4.png)
![simulator screen shot - iphone 6s plus - 2017-10-14 at 00 57 55](https://user-images.githubusercontent.com/32763714/31563045-347e2dec-b07b-11e7-83b5-907873a8726d.png)

**Comment by jasonjoh** [comment]
Thanks for the report. I'll look into this as soon as I can.

**Comment by jasonjoh** [comment]
@xcodeApps please try the code in the ios11-crash branch: https://github.com/jasonjoh/swift-tutorial/tree/ios11-crash.

It looks like there's an issue with the non-Safari embedded web view that the p2.oauth2 library uses. I was originally using that one because it required less tweaking on your app registration. I switched it to use the Safari-based view for the login UI.

For that to work, you have to register a custom URL scheme in your app registration, then configure your app to listen for that scheme. See the changes I made in this commit for details:

https://github.com/jasonjoh/swift-tutorial/commit/1f389415124546bb7b1e49dee01a4dd948e4dba0

This fixed the crash for me. Please let me know if it works for you.

**Comment by xcodeApps** [comment]
Thanks it makes sense to use the safari view I had raised issue to p2.oauth2.  Safari based view works fine.

**Comment by jasonjoh** [comment]
Thanks! I merged the update so hopefully folks shouldn't hit this anymore.
