### ISSUE TITLE
OAuth2: I don't have a refresh token, not trying to refresh

### ISSUE THREAD

**Issue by UHemarajU** [jasonjoh/swift-tutorial#5]
Hi,

I am using your code to run the sample, I given clientId and redirectUrl details, But I after running the app I am getting following issue and login screen not navigate to next.

**OAuth2: I don't have a refresh token, not trying to refresh**

Please help me on this. Thank you.

**Comment by jasonjoh** [comment]
That message just means there is no refresh token available, it's not an error. If you tap Log In you should see login.microsoftonline.com open in Safari.

**Comment by jasonjoh** [comment]
Closing this issue as I'm archiving this sample. We've retired the tutorial that this is based on and we're redirecting to the Microsoft Graph tutorial at https://docs.microsoft.com/graph/tutorials/ios-swift. The corresponding GitHub repo is https://github.com/microsoftgraph/msgraph-training-ios-swift.
