### ISSUE TITLE
Crash when clicking "sign in" on web view

### ISSUE THREAD

**Issue by FasterThanLlamas** [jasonjoh/swift-tutorial#7]
App crashes when clicking sign-in on the login page.  

Console:
2018-04-20 08:11:30.094467-0700 swift-tutorial[8080:1756454] [App] if we're in the real pre-commit handler we can't actually add any new fences due to CA restriction
(lldb) 

Crash is to AppDelegate with Thread 1: EXC_BAD_ACCESS (code=1, address=0x0)

Please let me know what further info you need.  Thanks for making this fantastic tutorial!

Same behavior on both simulator and physical device.  Tried workaround by using safari instead of embedded browser with same result.

Edit: Debug info
(lldb) po $arg1
error: Couldn't allocate space for the stack frame: Couldn't malloc: address space is full
error: errored out in DoExecute, couldn't PrepareToExecuteJITExpression

**Comment by jasonjoh** [comment]
Ok. I reproduce this. I'm probably going to rewrite the tutorial to use the Microsoft auth library, these issues always seem to crop up after XCode gets updated :)

**Comment by jasonjoh** [comment]
Let me know if that change doesn't fix it

**Comment by FasterThanLlamas** [comment]
Earlier today I was able to fix it by adjusting the AppDelegate function. I’ll post the new code tomorrow.

**Comment by FasterThanLlamas** [comment]
Here is the revised function in `AppDelegate` that fixed the crash/

    func application(_ app: UIApplication, open url: URL, options: [UIApplicationOpenURLOptionsKey : Any] = [:]) -> Bool {
    if url.scheme == "my-app" {
            let service = OutlookService.shared()
            service.handleOAuthCallback(url: url)
            return true
        }
        else {
            return false
        }
    }

**Comment by jasonjoh** [comment]
Yep, that looks like the change I made as well. Great minds and all :)
